### ISSUE TITLE
build on OS X 10.6.8 fails

### ISSUE THREAD

**Issue by davidak** [mdoege/mtmake-osx#1]
i want to build the latest stable release (0.4.11) of MT on Snow Leopard.

the dependencies are installed succesfull.

why is no compiler found?

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/2.8.12.2/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.
```

maybe this means it can only build on Yosemite?

```
  <built-in>:0: error: Unknown value ‘10.10’ of -mmacosx-version-min
```

full console output:
```
macbook:~ davidak$ git clone https://github.com/mdoege/mtmake-osx
Cloning into 'mtmake-osx'...
remote: Counting objects: 297, done.
remote: Total 297 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (297/297), 19.94 MiB | 3.53 MiB/s, done.
Resolving deltas: 100% (95/95), done.
Checking connectivity... done.
macbook:~ davidak$ cd mtmake-osx/
macbook:mtmake-osx davidak$ bash make_mac.sh 
Cloning into 'minetest-git'...
remote: Counting objects: 28446, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 28446 (delta 23), reused 0 (delta 0)
Receiving objects: 100% (28446/28446), 30.04 MiB | 4.20 MiB/s, done.
Resolving deltas: 100% (19214/19214), done.
Checking connectivity... done.
Cloning into 'minetest_game'...
remote: Counting objects: 3290, done.
remote: Total 3290 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3290/3290), 2.71 MiB | 100.00 KiB/s, done.
Resolving deltas: 100% (1416/1416), done.
Checking connectivity... done.
Already up-to-date.
Cloning into 'carbone'...
remote: Counting objects: 4892, done.
remote: Compressing objects: 100% (3790/3790), done.
remote: Total 4892 (delta 2537), reused 2478 (delta 1048)
Receiving objects: 100% (4892/4892), 4.33 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (2537/2537), done.
Checking connectivity... done.
Already up-to-date.
Cloning into 'Voxelgarden'...
remote: Counting objects: 2577, done.
remote: Total 2577 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2577/2577), 1.25 MiB | 73.00 KiB/s, done.
Resolving deltas: 100% (1496/1496), done.
Checking connectivity... done.
Already up-to-date.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
patching file src/game.cpp
Hunk #1 succeeded at 4090 (offset -3 lines).
Hunk #2 succeeded at 4106 (offset -3 lines).
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/local/Cellar/cmake/2.8.12.2/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/davidak/mtmake-osx/minetest-git/CMakeFiles/CMakeTmp

  

  Run Build Command:/usr/bin/make "cmTryCompileExec2119783852/fast"

  /usr/bin/make -f CMakeFiles/cmTryCompileExec2119783852.dir/build.make
  CMakeFiles/cmTryCompileExec2119783852.dir/build

  /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E cmake_progress_report
  /Users/davidak/mtmake-osx/minetest-git/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building C object
  CMakeFiles/cmTryCompileExec2119783852.dir/testCCompiler.c.o

  /usr/bin/cc -mmacosx-version-min=10.10 -march=core2 -msse4.1 -o
  CMakeFiles/cmTryCompileExec2119783852.dir/testCCompiler.c.o -c
  /Users/davidak/mtmake-osx/minetest-git/CMakeFiles/CMakeTmp/testCCompiler.c

  <built-in>:0: error: Unknown value ‘10.10’ of -mmacosx-version-min

  make[1]: *** [CMakeFiles/cmTryCompileExec2119783852.dir/testCCompiler.c.o]
  Error 1

  make: *** [cmTryCompileExec2119783852/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/davidak/mtmake-osx/minetest-git/CMakeFiles/CMakeOutput.log".
See also "/Users/davidak/mtmake-osx/minetest-git/CMakeFiles/CMakeError.log".
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
cp: bin/minetest: No such file or directory
make_mac.sh: line 52:   715 Segmentation fault      ./dylibbundler-0.4.4/dylibbundler -x minetest.app/Contents/Resources/bin/minetest -d ./minetest.app/Contents/libs/ -p @executable_path/../../libs/ >&/dev/null
======== otool =======
	@executable_path/../../libs/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	@executable_path/../../libs/libpng15.15.dylib (compatibility version 33.0.0, current version 33.0.0)
	@executable_path/../../libs/libSM.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	@executable_path/../../libs/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	@executable_path/../../libs/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	@executable_path/../../libs/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	@executable_path/../../libs/libvorbisfile.3.dylib (compatibility version 7.0.0, current version 7.6.0)
	@executable_path/../../libs/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.7.0)
	@executable_path/../../libs/libogg.0.dylib (compatibility version 9.0.0, current version 9.1.0)
	@executable_path/../../libs/libXxf86vm.1.dylib (compatibility version 2.0.0, current version 2.0.0)
cp: ../minetest-git/locale: No such file or directory
ls: minetest.app/Contents/libs/: No such file or directory
Number of included libraries (should be 18): 0
```

**Comment by mdoege** [comment]
Yes, sorry, I think you just need to remove the 10.10 compiler flags from the cmake line so it looks like this:

cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_FREETYPE=on -DENABLE_LEVELDB=on -DENABLE_GETTEXT=on -DENABLE_REDIS=on -DBUILD_SERVER=NO -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib"

**Comment by mdoege** [comment]
P.S. I've pushed an updated version of make_mac.sh to the repo that should work correctly on older OS X versions.

Thanks for reporting this!

**Comment by davidak** [comment]
that fixes the problem, the compiler is found and compiles.

thank you!

next problem appears after the translations:

**Comment by mdoege** [comment]
Thanks for the pull request, I've just merged it. Does this also fix the dylibbundler issue above or does it need to be rebuilt on older OS X versions?

**Comment by davidak** [comment]
great.

no, i have still the problem that the libs don't get copied into the app-bundle.
it runs on the mac i compiled it.

**Comment by mdoege** [comment]
OK, I've added a commit to always rebuild dylibbundler. I hope that fixes this issue.

**Comment by davidak** [comment]
looks good now. is 1 lib missing?

can i send you the binary?

```
[100%] Built target translations
======== building dylibbundler =======
rm -f *.o
rm -f ./dylibbundler
g++ -c -I./src ./src/Settings.cpp -o ./Settings.o
g++ -c -I./src ./src/DylibBundler.cpp -o ./DylibBundler.o
g++ -c -I./src ./src/Dependency.cpp -o ./Dependency.o
g++ -c -I./src ./src/main.cpp -o ./main.o
g++ -c -I./src ./src/Utils.cpp -o ./Utils.o
g++ -o ./dylibbundler ./Settings.o ./DylibBundler.o ./Dependency.o ./main.o ./Utils.o
======== otool =======
	@executable_path/../../libs/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
	@executable_path/../../libs/libpng12.0.dylib (compatibility version 36.0.0, current version 36.0.0)
	@executable_path/../../libs/libSM.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	@executable_path/../../libs/libICE.6.dylib (compatibility version 10.0.0, current version 10.0.0)
	@executable_path/../../libs/libX11.6.dylib (compatibility version 9.0.0, current version 9.0.0)
	@executable_path/../../libs/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	@executable_path/../../libs/libvorbisfile.3.dylib (compatibility version 7.0.0, current version 7.6.0)
	@executable_path/../../libs/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.7.0)
	@executable_path/../../libs/libogg.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	@executable_path/../../libs/libluajit-5.1.2.dylib (compatibility version 2.0.0, current version 2.0.3)
	@executable_path/../../libs/libXxf86vm.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	@executable_path/../../libs/libfreetype.6.dylib (compatibility version 10.0.0, current version 10.20.0)
	@executable_path/../../libs/libleveldb.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../../libs/libhiredis.0.10.dylib (compatibility version 0.0.0, current version 0.0.0)
Number of included libraries (should be 18): 17
```

**Comment by mdoege** [comment]
Here is my list of included libraries. It would be interesting to know what's missing from your build.

$ ll releases/minetest.app/Contents/libs/|nl
     1	total 10480
     2	-rwxr-xr-x  1 martin  staff   192528  4 Jan 21:56 libICE.6.dylib
     3	-rwxr-xr-x  1 martin  staff    84816  4 Jan 21:56 libSM.6.dylib
     4	-rwxr-xr-x  1 martin  staff  2364864  4 Jan 21:56 libX11.6.dylib
     5	-rwxr-xr-x  1 martin  staff    52416  4 Jan 21:56 libXau.6.dylib
     6	-rwxr-xr-x  1 martin  staff    65712  4 Jan 21:56 libXdmcp.6.dylib
     7	-rwxr-xr-x  1 martin  staff   146992  4 Jan 21:56 libXext.6.dylib
     8	-rwxr-xr-x  1 martin  staff    60960  4 Jan 21:56 libXxf86vm.1.dylib
     9	-rw-r--r--  1 martin  staff   540588  4 Jan 21:56 libfreetype.6.dylib
    10	-rw-r--r--  1 martin  staff    35816  4 Jan 21:56 libhiredis.0.10.dylib
    11	-rw-r--r--  1 martin  staff   207240  4 Jan 21:56 libjpeg.8.dylib
    12	-rw-r--r--  1 martin  staff   299160  4 Jan 21:56 libleveldb.1.dylib
    13	-rw-r--r--  1 martin  staff   557800  4 Jan 21:56 libluajit-5.1.2.dylib
    14	-rw-r--r--  1 martin  staff    24784  4 Jan 21:56 libogg.0.dylib
    15	-rw-r--r--  1 martin  staff   176956  4 Jan 21:56 libpng16.16.dylib
    16	-rw-r--r--  1 martin  staff    28220  4 Jan 21:56 libsnappy.1.dylib
    17	-rw-r--r--  1 martin  staff   162708  4 Jan 21:56 libvorbis.0.dylib
    18	-rw-r--r--  1 martin  staff    34908  4 Jan 21:56 libvorbisfile.3.dylib
    19	-rwxr-xr-x  1 martin  staff   291200  4 Jan 21:56 libxcb.1.dylib

To distribute the binary, maybe you could create a new release in your mtmake fork and upload it there (or fork the MT main repo like I do). Then I'll link to the release from my forum post.

**Comment by davidak** [comment]
the last one is missing: `libxcb.1.dylib`

the build works also on 10.9.5, just tested.

**Comment by mdoege** [comment]
Apparently libxcb is a relatively new addition to the X libraries, so maybe that is why 10.6 does not have it. No big deal then I suppose.

So you are saying the localizations don't work in your build? Or just on 10.9?

**Comment by davidak** [comment]
the translation in the launcher works, there is a little bit more translated in 0.4.11 like "Fancy Trees".

![bildschirmfoto 2015-01-05 um 13 25 59](https://cloud.githubusercontent.com/assets/91113/5613068/d8819fe8-94de-11e4-8294-8409bb351c10.png)

but ingame is nothing translated.

![bildschirmfoto 2015-01-05 um 13 30 25](https://cloud.githubusercontent.com/assets/91113/5613095/4a73d350-94df-11e4-9694-ea0d609e46c2.png)

![bildschirmfoto 2015-01-05 um 13 31 26](https://cloud.githubusercontent.com/assets/91113/5613096/51a58d94-94df-11e4-9f31-2231577c2aaa.png)

also, the performance is good with both build, but in my build while looking around with the mouse it stutters.

you can download it here: https://github.com/davidak/minetest/releases/tag/0.4.11

**Comment by mdoege** [comment]
It's called dirty because make_mac applies the fixfps patch (which is supposed to improve the stutters-when-looking-around issue a bit until a proper fix is found.) In git terminology, therefore the working directory is in a dirty state because it does not conform to commit that is checked out.

I've just noticed on Linux German translations are also broken in-game in 0.4.11, so I think this is not an OS X-specific issue. It's strange nobody has noticed this so far. Perhaps https://github.com/minetest/minetest/commit/ce4ed65a3948648b9baaabe205ddef0acd101b29 broke something?

**Comment by davidak** [comment]
i made a new issue for the translation bug: https://github.com/minetest/minetest/issues/2053

so we can close this one.

in dungeons it stutters also on 10.6.8, maybe that get's fixed in the future.

our mac builds should be in the official repo.

**Comment by mdoege** [comment]
The MT devs don't want any forum builds in the main repo. The past u64 problem and the frame rate limiter issue show that Irrlicht is still a bit buggy on OS X, so that is also why OS X is not officially supported right now. If we could produce an OS X build that behaves 100% identfical to a Linux build, maybe. But that would require fixes in Irrlicht I think.
