### ISSUE TITLE
Script fails to retrieve carbone

### ISSUE THREAD

**Issue by EricPDX** [mdoege/mtmake-osx#6]
Just a heads up, the script points to "https://git.gitorious.org/calinou/carbone.git", which isn't resolvable from my machine. Changing it to "https://gitorious.org/calinou/carbone.git" resolved the issue for me. I'm not sure if this affects other users, but I figured I'd pass it along just in case.

**Comment by mdoege** [comment]
Thanks for reporting, I've updated the URL.
